language: node_js

node_js:
  - 0.11
  - 0.10
  - 0.8

install:
  - npm install mocha-browser nico

before_script:
  - git clone git://github.com/spmjs/nico-cmd.git _theme
  - node_modules/.bin/nico build --theme _theme -C _theme/nico.js

script:
  - node_modules/.bin/mocha-browser _site/tests/runner.html -S

after_success:
